apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.ovn.org/pod-networks: '{"default":{"ip_addresses":["10.131.0.21/23"],"mac_address":"0a:58:0a:83:00:15","gateway_ips":["10.131.0.1"],"ip_address":"10.131.0.21/23","gateway_ip":"10.131.0.1"}}'
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.131.0.21"
          ],
          "mac": "0a:58:0a:83:00:15",
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.131.0.21"
          ],
          "mac": "0a:58:0a:83:00:15",
          "default": true,
          "dns": {}
      }]
    openshift.io/scc: restricted-v2
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  creationTimestamp: "2023-05-30T21:00:00Z"
  generateName: cockroachdb-
  labels:
    app: cockroachdb
    controller-revision-hash: cockroachdb-86b9568bb
    statefulset.kubernetes.io/pod-name: cockroachdb-0
  name: cockroachdb-0
  namespace: us-west-1
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: cockroachdb
    uid: cf22a192-4658-4ec1-96fb-8491899c6a2a
  resourceVersion: "374027"
  uid: cb87fbb5-9810-498e-9795-3d4ce35286a2
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - cockroachdb
          topologyKey: kubernetes.io/hostname
        weight: 100
  containers:
  - command:
    - /bin/bash
    - -ecx
    - exec /cockroach/cockroach start --insecure --logtostderr --certs-dir /cockroach/cockroach-certs
      --advertise-host $(hostname -f) --http-addr 0.0.0.0 --join cockroachdb-0.cockroachdb.eastus,cockroachdb-1.cockroachdb.eastus,cockroachdb-2.cockroachdb.eastus,cockroachdb-0.cockroachdb.us-west-1,cockroachdb-1.cockroachdb.us-west-1,cockroachdb-2.cockroachdb.us-west-1
      --locality region=us-west-1,zone=us-west-1 --cache $(expr $MEMORY_LIMIT_MIB
      / 4)MiB --max-sql-memory $(expr $MEMORY_LIMIT_MIB / 4)MiB
    env:
    - name: COCKROACH_CHANNEL
      value: kubernetes-multiregion
    - name: GOMAXPROCS
      valueFrom:
        resourceFieldRef:
          divisor: "1"
          resource: limits.cpu
    - name: MEMORY_LIMIT_MIB
      valueFrom:
        resourceFieldRef:
          divisor: 1Mi
          resource: limits.memory
    image: cockroachdb/cockroach:v23.1.2
    imagePullPolicy: IfNotPresent
    name: cockroachdb
    ports:
    - containerPort: 26257
      name: grpc
      protocol: TCP
    - containerPort: 8080
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 2
      httpGet:
        path: /health?ready=1
        port: http
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 1001280000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /cockroach/cockroach-data
      name: datadir
    - mountPath: /cockroach/cockroach-certs
      name: certs
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-m7flm
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: cockroachdb-0
  imagePullSecrets:
  - name: cockroachdb-dockercfg-pgjns
  nodeName: ip-10-10-9-15.us-west-2.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1001280000
    seLinuxOptions:
      level: s0:c36,c10
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: cockroachdb
  serviceAccountName: cockroachdb
  subdomain: cockroachdb
  terminationGracePeriodSeconds: 60
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: datadir
    persistentVolumeClaim:
      claimName: datadir-cockroachdb-0
  - name: certs
    secret:
      defaultMode: 448
      secretName: cockroachdb.node
  - name: kube-api-access-m7flm
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-05-30T21:00:00Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-05-30T21:00:00Z"
    message: 'containers with unready status: [cockroachdb]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-05-30T21:00:00Z"
    message: 'containers with unready status: [cockroachdb]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-05-30T21:00:00Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://efd572e0735bcfbea377ee068c47423eb09b7325e7b3ec63a7ceac46ebd5c6d9
    image: docker.io/cockroachdb/cockroach:v23.1.2
    imageID: docker.io/cockroachdb/cockroach@sha256:3ce0c7b4c010c02473ac29246b96be664041f0a36e9154dc82b4d053c2e00679
    lastState: {}
    name: cockroachdb
    ready: false
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-05-30T21:00:20Z"
  hostIP: 10.10.9.15
  phase: Running
  podIP: 10.131.0.21
  podIPs:
  - ip: 10.131.0.21
  qosClass: BestEffort
  startTime: "2023-05-30T21:00:00Z"
