apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cockroachdb
  namespace: openshift-operators
spec:
  channel: stable-5.x
  installPlanApproval: Automatic
  name: cockroachdb
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: cockroachdb.v5.0.4
  config:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi