kind: ExportedServiceSet
apiVersion: federation.maistra.io/v1
metadata:
  name: aws
  namespace: istio-system
spec:
  exportRules:
  - type: NameSelector
    nameSelector:
      namespace: azure-db-system
      name: cockroach-cockroachdb
  - type: NameSelector
    nameSelector:
      namespace: azure-db-system
      name: cockroach-cockroachdb-public
---
kind: ImportedServiceSet
apiVersion: federation.maistra.io/v1
metadata:
  name: azure
  namespace: istio-system
spec:
  importRules:
  - type: NameSelector
    importAsLocal: true
    nameSelector:
      namespace: aws-db-system
      name: cockroach-cockroachdb
  - type: NameSelector
    importAsLocal: true
    nameSelector:
      namespace: aws-db-system
      name: cockroach-cockroachdb-public